AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    cloud-stack

Globals:
    Api:
        Cors:
            AllowOrigin: "'*'"
            AllowHeaders: "'*'"
        Auth:
            AddDefaultAuthorizerToCorsPreflight: false
            DefaultAuthorizer: AdminAuthorizer
            Authorizers:
                AdminAuthorizer:
                    UserPoolArn: !GetAtt MyinUserPool.Arn
        MethodSettings:
            - ThrottlingRateLimit: 50
              ThrottlingBurstLimit: 50
              HttpMethod: '*'
              ResourcePath: '/*'
    Function:
        Timeout: 20

Resources:
    KanjiAttributesTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: KanjiAttributes
            PrimaryKey:
                Name: kanji
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 1

    JapaneseHttpApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
    JapaneseSyncRadicalTags:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/japanese
            Handler: radical.syncRadicalHandler
            Runtime: nodejs12.x
            Policies:
                - !Ref MongoDbParamReadPolicy
                - !Ref SyncBucketReadDeletePolicy
            Events:
                SyncRadical:
                    Type: S3
                    Properties:
                        Bucket: !Ref SyncBucket
                        Events: s3:ObjectCreated:*
                        Filter:
                            S3Key:
                                Rules:
                                    - Name: prefix
                                      Value: radical-tags

    JapaneseUpdateRadical:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/japanese
            Handler: radical.updateRadicalHandler
            Runtime: nodejs12.x
            Policies: !Ref MongoDbParamReadPolicy
            Events:
                UpdateRadical:
                    Type: Api
                    Properties:
                        RestApiId: !Ref JapaneseHttpApi
                        Method: POST
                        Path: /radical
    JapaneseGetRadical:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/japanese
            Handler: radical.getRadicalHandler
            Runtime: nodejs12.x
            Policies: !Ref MongoDbParamReadPolicy
            Events:
                GetRadical:
                    Type: Api
                    Properties:
                        RestApiId: !Ref JapaneseHttpApi
                        Method: GET
                        Path: /radical
    JapaneseGetRadicalList:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/japanese
            Handler: radical.getRadicalListHandler
            Runtime: nodejs12.x
            Policies: !Ref MongoDbParamReadPolicy
            Events:
                GetRadical:
                    Type: Api
                    Properties:
                        RestApiId: !Ref JapaneseHttpApi
                        Method: GET
                        Path: /radical/list
                        Auth:
                            Authorizer: NONE

    # MongoDb Parameter Policy
    MongoDbParamReadPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Action: ssm:GetParameter
                      Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mongodb_*'
    SyncBucketReadDeletePolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Action:
                          - s3:GetObject
                          - s3:DeleteObject
                      Resource: '*' # Cannot use SyncBucket Ref here, cyclic dependency

    SyncBucket:
        Type: AWS::S3::Bucket

    # User Pool
    MyinUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            AdminCreateUserConfig:
                AllowAdminCreateUserOnly: true
    MyinUserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            UserPoolId: !Ref MyinUserPool
            AllowedOAuthFlowsUserPoolClient: true
            SupportedIdentityProviders:
                - COGNITO
            AllowedOAuthFlows:
                - implicit
            AllowedOAuthScopes:
                - email
                - openid
            CallbackURLs:
                - http://localhost:4200/login
                - https://myin142.github.io/admin/login
    MyinUserPoolDomain:
        Type: AWS::Cognito::UserPoolDomain
        Properties:
            Domain: myin-user-domain
            UserPoolId: !Ref MyinUserPool
