image: node

cache:
    paths:
        - node_modules/

workflow:
    rules:
        - if: $CI_EXTERNAL_PULL_REQUEST_IID
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
    - test
    - e2e
    - deploy

before_script:
    - HEAD=$CI_COMMIT_SHA
    - BASE=$CI_COMMIT_BEFORE_SHA
    - if [ "$BASE" == "0000000000000000000000000000000000000000" ]; then BASE="$HEAD~1"; fi
    - BASE_HEAD_ARGS="--base=$BASE --head=$HEAD"
    - echo $BASE_HEAD_ARGS
    - npm i

test:
    stage: test
    script:
        - npm test -- $BASE_HEAD_ARGS

lint:
    stage: test
    script:
        - npm run lint -- $BASE_HEAD_ARGS

e2e:
    image: cypress/base:12
    stage: e2e
    script:
        - npm run e2e -- $BASE_HEAD_ARGS
    rules:
        - if: $CI_EXTERNAL_PULL_REQUEST_IID

deploy:
    stage: deploy
    script:
        - npm run build -- $BASE_HEAD_ARGS
        - ./scripts/clone-website "$GITHUB_TOKEN" "ci-web"
        - ./scripts/deploy-website ci-web
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
