include:
    remote: 'https://github.com/myin142/gitlab-templates/raw/master/default-merge-js.yml'

cache:
    keys:
        files:
            - package-lock.json
    paths:
        - node_modules/
        - tmp/

stages:
    - test
    - e2e
    - deploy

before_script:
    - CYPRESS_CACHE_FOLDER=./tmp/Cypress npm i

test:
    stage: test
    extends: .prepare_nx_affected
    script:
        - npm test -- $NX_BASE_ARGS

lint:
    stage: test
    extends: .prepare_nx_affected
    script:
        - npm run lint -- $NX_BASE_ARGS

e2e:
    image: cypress/base
    stage: e2e
    extends: .prepare_nx_affected
    script:
        - CYPRESS_CACHE_FOLDER=./tmp/Cypress npm run e2e -- $NX_BASE_ARGS
    rules:
        - if: $CI_EXTERNAL_PULL_REQUEST_IID

deploy:
    stage: deploy
    extends: .prepare_nx_affected
    script:
        - npm run build -- $NX_BASE_ARGS
        - ./scripts/clone-website "$GITHUB_TOKEN" "ci-web"
        - ./scripts/deploy-website ci-web
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
