image: node

cache:
    paths:
        - node_modules/
        - ~/.cache/Cypress

include:
    - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
    - test
    - e2e
    - deploy

before_script:
    - BASE=$CI_COMMIT_BEFORE_SHA
    - if [ -z "$BASE" ]; then BASE="origin/master"; fi
    - HEAD=$CI_COMMIT_SHA
    - echo $BASE
    - echo $HEAD
    - BASE_HEAD_ARGS="--base=$BASE --head=$HEAD"
    - npm i

test:
    stage: test
    script:
        #- npm run lint -- $BASE_HEAD_ARGS
        - npm test -- $BASE_HEAD_ARGS

e2e:
    stage: e2e
    script:
        - npm run e2e -- $BASE_HEAD_ARGS
    #only:
    #    - merge_requests

deploy:
    stage: deploy
    script:
        - npm run build -- $BASE_HEAD_ARGS
        - ./scripts/clone-website "$GITHUB_TOKEN" "ci-web"
        - ./scripts/deploy-website ci-web
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
