language: node_js
node_js:
    - 'node'

cache: npm

stages:
    - test
    - name: deploy
      if: branch = master AND type = push
    - name: integration
      if: branch = master AND type = pull
    - name: nightly # Run daily for testing if server is operating normally
      if: type = cron

before_script:
    - COMMITS=($(echo $TRAVIS_COMMIT_RANGE | sed 's/\.\+/ /'))
    - BASE=${COMMITS[0]}
    - if [ -z "$BASE" ]; then BASE="origin/master"; fi
    - HEAD=${COMMITS[1]}
    - if [ -z "$HEAD" ]; then HEAD="$TRAVIS_COMMIT"; fi
    - echo $BASE
    - echo $HEAD
    - BASE_HEAD_ARGS="--base=$BASE --head=$HEAD"

jobs:
    include:
        - stage: test
          script:
              - npm test -- $BASE_HEAD_ARGS
              - npm run lint -- $BASE_HEAD_ARGS
        - stage: deploy
          script:
              - npm run build
              - ./scripts/prepare-deploy gh-deploy 
              deploy:
                provider: pages
                skip_cleanup: true
                github_token: $GITHUB_TOKEN
                target_branch: master
                local_dir: gh-deploy
                repo: myin142/myin142.github.io
                on:
                  branch: master
        - stage: integration
          script: npm run e2e -- $BASE_HEAD_ARGS
        - stage: nightly
          script: npm run nightly -- $BASE_HEAD_ARGS
