language: node_js
node_js:
    - 'node'

cache: npm

jobs:
    include:
        - script:
              - echo $TRAVIS_COMMIT
              - echo $TRAVIS_COMMIT_RANGE
              - npm test
        - script: npm run build
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              target_branch: master
              local_dir: dist/apps/
              repo: myin142/myin142.github.io
              on:
                  branch: travis
        - if: branch = master
          script: npm run e2e
