language: node_js
node_js:
    - 'node'

cache: npm

before_script:
    - COMMITS=($(echo $TRAVIS_COMMIT_RANGE | sed 's/\.\+/ /'))
    - BASE=${COMMITS[0]}
    - HEAD=${COMMITS[1]}
    - echo $BASE
    - echo $HEAD

jobs:
    include:
        - script: npm test -- --base=$BASE --head=$HEAD
        - script:
              - npm run build -- --base=$BASE --head=$HEAD
              - ./scripts/gh-deploy $GITHUB_TOKEN
        - if: branch = master
          script: npm run e2e -- --base=$BASE --head=$HEAD
