version: 2.1
commands:
    install-with-cache:
        description: 'Npm install with restorable cache'
        steps:
            - run: node --version
            - restore_cache:
                  keys:
                      - node-cache-{{ checksum "package-lock.json" }}
            - run: npm install
            - save_cache:
                  key: node-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules/
jobs:
    test:
        docker:
            - image: 'node:12'
        steps:
            - checkout
            - install-with-cache
            - run: npm test
    deploy:
        docker:
            - image: 'node:12'
        steps:
            - checkout
            - install-with-cache
            - run: npm run build
            - run: sh ./scripts/gh-deploy $GH_TOKEN
    integration:
        docker:
            - image: 'node:12'
        steps:
            - checkout
            - install-with-cache
            - run: npm run e2e
workflows:
    test-and-deploy:
        jobs:
            - test
            - deploy:
                  requires:
                      - test
            - integration:
                  requires:
                      - deploy
                  filters:
                      branches:
                          only:
                              - master
