version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
    deploy:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  cache-path: ./node_modules
            - run: npm run build
            - run: sh ./scripts/gh-deploy $GH_TOKEN
    test:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  cache-path: ./node_modules
            - run: npm test
    integration:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  cache-path: ./node_modules
            - run: npm run e2e

workflows:
    test-and-deploy:
        jobs:
            - test
            - deploy:
                  requires:
                      - test
            - integration:
                  requires:
                      - deploy
                  filters:
                      branches:
                          only:
                              - master
