version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
    test:
        executor: node/default
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - node-cache-{{ checksum "package-lock.json" }}
            - node/install-packages
            - save_cache:
                  key: node-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules/
            - run: npm test
    deploy:
        executor: node/default
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - node-cache-{{ checksum "package-lock.json" }}
            - node/install-packages
            - run: npm run build
            - run: sh ./scripts/gh-deploy $GH_TOKEN
    integration:
        executor: node/default
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - node-cache-{{ checksum "package-lock.json" }}
            - node/install-packages
            - run: npm run e2e
            - restore_cache:
                  keys:
                      - node-cache-{{ checksum "package-lock.json" }}

workflows:
    test-and-deploy:
        jobs:
            - test
            - deploy:
                  requires:
                      - test
            - integration:
                  requires:
                      - deploy
                  filters:
                      branches:
                          only:
                              - master
