#!/bin/sh

set -e

BRANCH="master"
REPO_TARGET="${1:-ci-website}"

if [ -z $REPO_TARGET ]; then
    echo "Directory name needed"
    exit 1
fi

if [ -d dist/apps ]; then
    echo "Copying Folders"
    npm run copy-apps -- --target $REPO_TARGET --exclude aws-app sync

    # Copy files for static hosting
    echo "Copy required static files"
    cp dist/apps/public/assets/* $REPO_TARGET -r

    # Append redirect script to every app index file
    # needed for static hosting
    echo "Apply required changes to index.html files"
    find $REPO_TARGET/* -maxdepth 1 -type f -name "index.html" \
        -exec sh -c 'echo "<script src="/public/assets/redirect.js" type="text/javascript"></script>" >> {}' \;

    echo "$REPO_TARGET ready to be deployed"
fi

cd $REPO_TARGET
git add -f .

if git commit -m "Deploy with Github CI"; then
    echo "Pushing to Github Pages"
    git push -f origin $BRANCH
else
    echo "Skip deployment. Nothing changed"
fi