#!/bin/sh

TOKEN="$1"
REPO="https://$TOKEN@github.com/myin142/myin142.github.io.git"
REPO_TARGET="ci-website"
BRANCH=master

echo "Deploying to Github Pages"

git config --global user.email "build@circleci.com"
git config --global user.name "Circle CI"

git clone --quiet --branch=$BRANCH $REPO $REPO_TARGET

echo "Copying Folders"

# Copy all apps for now
cp "dist/apps/*" $REPO_TARGET -r

cd $REPO_TARGET
git add -f .

if git commit -m "Deploy with CircleCI"; then
    echo "Pushing to Github Pages"
    git push -f origin $BRANCH
else
    echo "Skip deployment. Nothing changed"
fi