#!/bin/sh

DYNAMO=http://localhost:8000

cd cloud
docker-compose up --remove-orphans -d
aws dynamodb create-table \
    --cli-input-json file://local/kanji-attributes-table.json \
    --endpoint-url "$DYNAMO"
node ../dist/apps/sync/main.js local/kanji.json --endpoint "$DYNAMO"

# Running Applications
sam build && sam local start-api --docker-network host

# Stopping everything
docker-compose down
